
import { useEffect, useMemo, useState } from 'react'
import { PageHead } from './Nav'
import { addFeedLog, addPoopLog, addSleepLog, buildDayAggs, deleteLog, exportLogsCsv, formatDateTimeLabel, formatDuration, formatDurationMin, formatSleepDuration, readLogs, readSession, readSleepSession, writeSession, writeSleepSession, type DailyLog, type FeedLog, type PoopLog, type PoopConsistency, type SleepLog, type SleepType } from '../lib/dailyLogs'
function toDateKey(d: Date): string { const y=d.getFullYear(); const m=String(d.getMonth()+1).padStart(2,'0'); const day=String(d.getDate()).padStart(2,'0'); return `${y}-${m}-${day}` }
function toTimeLabel(d: Date): string { return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}` }
function formatTick(sec:number): string { const m=String(Math.floor(sec/60)).padStart(2,'0'); const s=String(sec%60).padStart(2,'0'); return `${m}:${s}` }
function SimpleLineChart({ data, lines, height=132 }: { data:any[]; lines:{key:string;color:string;label:string}[]; height?:number }) {
  const width=520; const pad={top:12,right:12,bottom:22,left:28}; const innerW=width-pad.left-pad.right; const innerH=height-pad.top-pad.bottom
  const maxMap=new Map<string,number>(); for(const l of lines){ const vals=data.map((d:any)=>Number(d[l.key]||0)); maxMap.set(l.key, Math.max(1,...vals)) }
  function xAt(i:number){ if(data.length===1) return pad.left+innerW/2; return pad.left+(i/(data.length-1))*innerW }
  function yAt(v:number,max:number){ return pad.top+innerH-(v/max)*innerH }
  return (<div className="chart-wrap"><svg viewBox={`0 0 ${width} ${height}`} className="chart-svg">{[0,0.5,1].map(r=>{ const y=pad.top+innerH*r; return <line key={r} x1={pad.left} x2={width-pad.right} y1={y} y2={y} stroke="#ffe0ec" strokeDasharray={r===1?'0':'4 4'} />})}{lines.map(l=>{ const max=maxMap.get(l.key)||1; const pts=data.map((d:any,i:number)=>`${xAt(i)},${yAt(Number(d[l.key]||0),max)}`).join(' '); return <polyline key={l.key} fill="none" stroke={l.color} strokeWidth={2.2} strokeLinejoin="round" strokeLinecap="round" points={pts} />})}{lines.map(l=>{ const max=maxMap.get(l.key)||1; return data.map((d:any,i:number)=>{ const cx=xAt(i); const cy=yAt(Number(d[l.key]||0),max); return <circle key={l.key+i} cx={cx} cy={cy} r={3} fill={l.color} stroke="#fff" strokeWidth={1.2} />})})}{data.map((lb:any,i:number)=><text key={String(lb.label)+i} x={xAt(i)} y={height-4} textAnchor="middle" fontSize={9} fill="#8b7a89">{String(lb.label).slice(3)}</text>)}</svg><div className="chart-legend">{lines.map(l=><span key={l.key} className="chart-legend-item"><i style={{background:l.color}}/>{l.label}</span>)}</div></div>)
}
export default function DailyLogsView({ logs, onLogsChange }: { logs: DailyLog[]; onLogsChange:(next: DailyLog[])=>void }) {
  const [session,setSession]=useState(()=>readSession()); const [sleepSession,setSleepSession]=useState(()=>readSleepSession()); const [tick,setTick]=useState(0); const [feedNote,setFeedNote]=useState(''); const [poopConsistency,setPoopConsistency]=useState<PoopConsistency>(''); const [poopNote,setPoopNote]=useState(''); const [sleepNote,setSleepNote]=useState(''); const [sleepType,setSleepType]=useState<SleepType>(''); const [listFilter,setListFilter]=useState<'all'|'feed'|'poop'|'sleep'>('all'); const [dateFilter,setDateFilter]=useState<string>(toDateKey(new Date())); const [showAllDates,setShowAllDates]=useState(false); const [feedDays,setFeedDays]=useState<7|14|30>(7); const [poopDays,setPoopDays]=useState<7|14|30>(30); const [sleepDays,setSleepDays]=useState<7|14|30>(7); const [hint,setHint]=useState(''); const [showManualFeed,setShowManualFeed]=useState(false); const [manualFeedDate,setManualFeedDate]=useState(toDateKey(new Date())); const [manualFeedStart,setManualFeedStart]=useState('10:00'); const [manualFeedEnd,setManualFeedEnd]=useState('10:15'); const [manualFeedNote,setManualFeedNote]=useState(''); const [showManualPoop,setShowManualPoop]=useState(false); const [manualPoopDate,setManualPoopDate]=useState(toDateKey(new Date())); const [manualPoopTime,setManualPoopTime]=useState(toTimeLabel(new Date())); const [manualPoopCons,setManualPoopCons]=useState<PoopConsistency>('正常'); const [manualPoopNote,setManualPoopNote]=useState(''); const [showManualSleep,setShowManualSleep]=useState(false); const [manualSleepDate,setManualSleepDate]=useState(toDateKey(new Date())); const [manualSleepStart,setManualSleepStart]=useState('21:30'); const [manualSleepEnd,setManualSleepEnd]=useState('06:10'); const [manualSleepType,setManualSleepType]=useState<SleepType>('夜间'); const [manualSleepNote,setManualSleepNote]=useState(''); const [exportStart,setExportStart]=useState(()=>{ const d=new Date(); d.setDate(d.getDate()-29); return toDateKey(d)}); const [exportEnd,setExportEnd]=useState(()=>toDateKey(new Date()))
  const isFeeding=!!session; const isSleeping=!!sleepSession; const feedingSec=useMemo(()=>{ if(!session) return 0; return Math.max(0,Math.floor((Date.now()-new Date(session.startAt).getTime())/1000))},[session,tick]); const sleepingSec=useMemo(()=>{ if(!sleepSession) return 0; return Math.max(0,Math.floor((Date.now()-new Date(sleepSession.startAt).getTime())/1000))},[sleepSession,tick])
  useEffect(()=>{ if(!session && !sleepSession) return; const id=window.setInterval(()=>setTick(v=>v+1),1000); return ()=>window.clearInterval(id)},[session,sleepSession])
  function refresh(){ onLogsChange(readLogs()) }
  function handleStartFeed(){ const s={startAt:new Date().toISOString()}; writeSession(s); setSession(s); setHint('已开始计时，再次点击“停止”结束。'); window.setTimeout(()=>setHint(''),2500)}
  function handleStopFeed(){ if(!session) return; const start=new Date(session.startAt); const end=new Date(); if(end.getTime()<=start.getTime()){ setHint('结束时间需晚于开始时间'); return } const dur=Math.round((end.getTime()-start.getTime())/1000); if(!window.confirm('结束本次喝奶 '+formatDuration(dur)+'？')) return; addFeedLog(start,end,feedNote); writeSession(null); setSession(null); setFeedNote(''); refresh(); setHint('已记录喝奶 '+formatDuration(dur)); window.setTimeout(()=>setHint(''),2500)}
  function handleCancelFeed(){ if(!window.confirm('取消本次计时？')) return; writeSession(null); setSession(null); setHint('已取消本次计时'); window.setTimeout(()=>setHint(''),2000)}
  function handleStartSleep(){ if(isSleeping) return; const s={startAt:new Date().toISOString()}; writeSleepSession(s); setSleepSession(s); setHint('已开始记录睡眠，再次点击“醒来”结束。'); window.setTimeout(()=>setHint(''),2500)}
  function handleStopSleep(){ if(!sleepSession) return; const start=new Date(sleepSession.startAt); const end=new Date(); if(end.getTime()<=start.getTime()){ setHint('醒来时间需晚于入睡时间'); return } const dur=Math.round((end.getTime()-start.getTime())/1000); if(dur<=0){ setHint('时长需大于0'); return } if(dur>86400){ if(!window.confirm('睡眠超过24小时，确认无误？')) return } if(!window.confirm('结束本次睡眠 '+formatSleepDuration(dur)+'？')) return; addSleepLog(start,end,sleepType,sleepNote); writeSleepSession(null); setSleepSession(null); setSleepNote(''); refresh(); setHint('已记录睡眠 '+formatSleepDuration(dur)); window.setTimeout(()=>setHint(''),2500)}
  function handleCancelSleep(){ if(!window.confirm('取消本次睡眠？')) return; writeSleepSession(null); setSleepSession(null); setHint('已取消本次睡眠'); window.setTimeout(()=>setHint(''),2000)}
  function handleAddPoop(){ const last=logs.find(l=>l.type==='poop') as PoopLog|undefined; if(last && Date.now()-new Date(last.createdAt).getTime()<60000){ if(!window.confirm('刚刚已记录，确定再记一次？')) return } addPoopLog(new Date(),poopConsistency,poopNote); refresh(); setPoopNote(''); setHint('已记录拉屎 '+toTimeLabel(new Date())); window.setTimeout(()=>setHint(''),2500)}
  function handleDelete(id:string){ if(!window.confirm('删除这条记录？')) return; deleteLog(id); refresh()}
  function handleManualFeedSubmit(){ const start=new Date(manualFeedDate+'T'+manualFeedStart+':00'); const end=new Date(manualFeedDate+'T'+manualFeedEnd+':00'); if(isNaN(start.getTime())||isNaN(end.getTime())){ setHint('时间格式不正确'); return } if(end.getTime()<=start.getTime()){ setHint('结束时间需晚于开始时间'); return } addFeedLog(start,end,manualFeedNote); refresh(); setShowManualFeed(false); setManualFeedNote(''); setHint('已补录喝奶'); window.setTimeout(()=>setHint(''),2000)}
  function handleManualPoopSubmit(){ const dt=new Date(manualPoopDate+'T'+manualPoopTime+':00'); if(isNaN(dt.getTime())){ setHint('时间格式不正确'); return } addPoopLog(dt,manualPoopCons,manualPoopNote); refresh(); setShowManualPoop(false); setManualPoopNote(''); setHint('已补录拉屎'); window.setTimeout(()=>setHint(''),2000)}
  function handleManualSleepSubmit(){ const start=new Date(manualSleepDate+'T'+manualSleepStart+':00'); let end=new Date(manualSleepDate+'T'+manualSleepEnd+':00'); if(isNaN(start.getTime())||isNaN(end.getTime())){ setHint('时间格式不正确'); return } if(end.getTime()<=start.getTime()){ end=new Date(end.getTime()+86400000); } if(end.getTime()<=start.getTime()){ setHint('醒来时间需晚于入睡时间'); return } const dur=Math.round((end.getTime()-start.getTime())/1000); if(dur>86400){ if(!window.confirm('睡眠超过24小时，确认无误？')) return } addSleepLog(start,end,manualSleepType,manualSleepNote); refresh(); setShowManualSleep(false); setManualSleepNote(''); setHint('已补录睡眠 '+formatSleepDuration(dur)); window.setTimeout(()=>setHint(''),2000)}
  const filteredList=useMemo(()=>{ let arr=logs; if(listFilter!=='all') arr=arr.filter(l=>l.type===listFilter); if(!showAllDates) arr=arr.filter(l=>l.date===dateFilter); return arr},[logs,listFilter,dateFilter,showAllDates])
  const feedAggs=useMemo(()=>buildDayAggs(logs,feedDays),[logs,feedDays]); const poopAggs=useMemo(()=>buildDayAggs(logs,poopDays),[logs,poopDays]); const sleepAggs=useMemo(()=>buildDayAggs(logs,sleepDays),[logs,sleepDays])
  const feedTotals=useMemo(()=>{ const c=feedAggs.reduce((s,a)=>s+a.feedCount,0); const m=feedAggs.reduce((s,a)=>s+a.feedMin,0); return {c,m,avg:c?(m/c).toFixed(1):'0'}},[feedAggs])
  const poopTotals=useMemo(()=>{ const c=poopAggs.reduce((s,a)=>s+a.poopCount,0); return {c,avg:(c/poopAggs.length).toFixed(1)}},[poopAggs]); const sleepTotals=useMemo(()=>{ const m=sleepAggs.reduce((s,a)=>s+a.sleepMin,0); const h=(m/60).toFixed(1); return {m,h,avg:(m/sleepAggs.length).toFixed(0)}},[sleepAggs])
  return (<>
    <PageHead title="日常记录" desc="一键记喝奶、拉屎与睡觉，自动计时与趋势，支持补录与报表导出。关闭后重开自动续算。" />
    {hint && <div className="note-banner" style={{marginBottom:12}}>{hint}</div>}
    {isFeeding && <div className="feeding-bar"><span className="feeding-dot"/>喝奶计时中 {formatTick(feedingSec)} · 开始于 {toTimeLabel(new Date(session!.startAt))}<button className="btn" style={{marginLeft:'auto'}} onClick={handleCancelFeed}>取消</button></div>}
    {isSleeping && <div className="feeding-bar" style={{background:'#eef4ff', borderColor:'#d7e4fb', color:'#35609e'}}><span className="feeding-dot" style={{background:'#4d96ff'}}/>睡觉中 {formatTick(sleepingSec)} · 入睡于 {toTimeLabel(new Date(sleepSession!.startAt))}<button className="btn" style={{marginLeft:'auto'}} onClick={handleCancelSleep}>取消</button></div>}
    <div className="log-actions">
      <div className="log-btn-card"><div className="log-btn-title">🍼 喝奶</div><p className="log-btn-desc">{isFeeding?'计时中 '+formatTick(feedingSec):'点击开始，结束自动算时长'}</p>{!isFeeding?(<button className="btn primary log-main-btn" onClick={handleStartFeed}>开始喝奶</button>):(<button className="btn primary log-main-btn feeding" onClick={handleStopFeed}>停止 {formatTick(feedingSec)}</button>)}<input className="select" placeholder="备注可选，如左/右、奶量" value={feedNote} onChange={e=>setFeedNote(e.target.value)} style={{marginTop:8}} /></div>
      <div className="log-btn-card"><div className="log-btn-title">💩 拉屎</div><p className="log-btn-desc">一键记录，精确到分钟</p><button className="btn primary log-main-btn" style={{background:'linear-gradient(135deg,#8b6cff,#a48bff)'}} onClick={handleAddPoop}>记录拉屎</button><div className="action-bar" style={{marginTop:8}}><select className="select" value={poopConsistency} onChange={e=>setPoopConsistency(e.target.value as PoopConsistency)} style={{flex:1}}><option value="">性状可选</option><option value="正常">正常</option><option value="稀">稀</option><option value="硬">硬</option><option value="水样">水样</option></select></div><input className="select" placeholder="备注可选" value={poopNote} onChange={e=>setPoopNote(e.target.value)} style={{marginTop:8}} /></div>
      <div className="log-btn-card"><div className="log-btn-title">🌙 睡觉</div><p className="log-btn-desc">{isSleeping?'睡觉中 '+formatTick(sleepingSec)+' · 点醒来结束':'点击入睡，醒来时结束算时长'}</p>{!isSleeping?(<button className="btn primary log-main-btn" style={{background:'linear-gradient(135deg,#4d96ff,#6bc1ff)'}} onClick={handleStartSleep}>开始睡觉</button>):(<button className="btn primary log-main-btn feeding" style={{background:'linear-gradient(135deg,#4d96ff,#6bc1ff)'}} onClick={handleStopSleep}>醒来 {formatTick(sleepingSec)}</button>)}<div className="action-bar" style={{marginTop:8}}><select className="select" value={sleepType} onChange={e=>setSleepType(e.target.value as SleepType)} style={{flex:1}}><option value="">标签可选</option><option value="夜间">夜间</option><option value="午睡">午睡</option><option value="小睡">小睡</option></select></div><input className="select" placeholder="备注可选" value={sleepNote} onChange={e=>setSleepNote(e.target.value)} style={{marginTop:8}} /></div>
    </div>
    <div className="action-bar" style={{marginBottom:12}}><button className="btn" onClick={()=>setShowManualFeed(v=>!v)}>补录喝奶</button><button className="btn" onClick={()=>setShowManualPoop(v=>!v)}>补录拉屎</button><button className="btn" onClick={()=>setShowManualSleep(v=>!v)}>补录睡觉</button></div>
    {showManualFeed && <div className="setting-card"><div className="setting-title">补录喝奶</div><div className="action-bar"><input className="select" type="date" value={manualFeedDate} onChange={e=>setManualFeedDate(e.target.value)} /><input className="select" type="time" value={manualFeedStart} onChange={e=>setManualFeedStart(e.target.value)} /><span style={{alignSelf:'center'}}>至</span><input className="select" type="time" value={manualFeedEnd} onChange={e=>setManualFeedEnd(e.target.value)} /></div><input className="select" placeholder="备注可选" value={manualFeedNote} onChange={e=>setManualFeedNote(e.target.value)} style={{marginTop:8}} /><div className="action-bar"><button className="btn primary" onClick={handleManualFeedSubmit}>确认补录</button><button className="btn" onClick={()=>setShowManualFeed(false)}>取消</button></div></div>}
    {showManualPoop && <div className="setting-card"><div className="setting-title">补录拉屎</div><div className="action-bar"><input className="select" type="date" value={manualPoopDate} onChange={e=>setManualPoopDate(e.target.value)} /><input className="select" type="time" value={manualPoopTime} onChange={e=>setManualPoopTime(e.target.value)} /><select className="select" value={manualPoopCons} onChange={e=>setManualPoopCons(e.target.value as PoopConsistency)}><option value="">性状</option><option value="正常">正常</option><option value="稀">稀</option><option value="硬">硬</option><option value="水样">水样</option></select></div><input className="select" placeholder="备注可选" value={manualPoopNote} onChange={e=>setManualPoopNote(e.target.value)} style={{marginTop:8}} /><div className="action-bar"><button className="btn primary" onClick={handleManualPoopSubmit}>确认补录</button><button className="btn" onClick={()=>setShowManualPoop(false)}>取消</button></div></div>}
    {showManualSleep && <div className="setting-card"><div className="setting-title">补录睡觉</div><div className="action-bar"><input className="select" type="date" value={manualSleepDate} onChange={e=>setManualSleepDate(e.target.value)} /><input className="select" type="time" value={manualSleepStart} onChange={e=>setManualSleepStart(e.target.value)} /><span style={{alignSelf:'center'}}>至</span><input className="select" type="time" value={manualSleepEnd} onChange={e=>setManualSleepEnd(e.target.value)} /><select className="select" value={manualSleepType} onChange={e=>setManualSleepType(e.target.value as SleepType)}><option value="">标签</option><option value="夜间">夜间</option><option value="午睡">午睡</option><option value="小睡">小睡</option></select></div><input className="select" placeholder="备注可选" value={manualSleepNote} onChange={e=>setManualSleepNote(e.target.value)} style={{marginTop:8}} /><div className="action-bar"><button className="btn primary" onClick={handleManualSleepSubmit}>确认补录</button><button className="btn" onClick={()=>setShowManualSleep(false)}>取消</button></div></div>}
    <div className="setting-card"><div className="setting-title">喂养趋势（默认近7天）</div><div className="action-bar" style={{marginBottom:8}}>{([7,14,30] as const).map(d=><button key={d} className={feedDays===d?'btn primary':'btn'} onClick={()=>setFeedDays(d)}>{d}天</button>)}<span className="chip" style={{marginLeft:'auto'}}>共 {feedTotals.c} 次 · {feedTotals.m.toFixed(0)} 分 · 均 {feedTotals.avg} 分/次</span></div><SimpleLineChart data={feedAggs} lines={[{key:'feedCount',color:'#ff6b9d',label:'次数'},{key:'feedMin',color:'#4d96ff',label:'分钟'}]} /></div>
    <div className="setting-card"><div className="setting-title">排便趋势（默认近30天）</div><div className="action-bar" style={{marginBottom:8}}>{([7,14,30] as const).map(d=><button key={d} className={poopDays===d?'btn primary':'btn'} onClick={()=>setPoopDays(d)}>{d}天</button>)}<span className="chip" style={{marginLeft:'auto'}}>共 {poopTotals.c} 次 · 日均 {poopTotals.avg} 次</span></div><SimpleLineChart data={poopAggs} lines={[{key:'poopCount',color:'#8b6cff',label:'拉屎次数'}]} /></div>
    <div className="setting-card"><div className="setting-title">睡眠趋势（默认近7天，方案A归起始日）</div><div className="action-bar" style={{marginBottom:8}}>{([7,14,30] as const).map(d=><button key={d} className={sleepDays===d?'btn primary':'btn'} onClick={()=>setSleepDays(d)}>{d}天</button>)}<span className="chip" style={{marginLeft:'auto'}}>共 {sleepTotals.h} 小时 · 日均 {sleepTotals.avg} 分</span></div><SimpleLineChart data={sleepAggs} lines={[{key:'sleepMin',color:'#4d96ff',label:'睡眠分钟'}]} /></div>
    <div className="setting-card"><div className="setting-title">记录列表</div><div className="action-bar"><button className={listFilter==='all'?'btn primary':'btn'} onClick={()=>setListFilter('all')}>全部</button><button className={listFilter==='feed'?'btn primary':'btn'} onClick={()=>setListFilter('feed')}>仅喝奶</button><button className={listFilter==='poop'?'btn primary':'btn'} onClick={()=>setListFilter('poop')}>仅拉屎</button><button className={listFilter==='sleep'?'btn primary':'btn'} onClick={()=>setListFilter('sleep')}>仅睡觉</button><input className="select" type="date" value={dateFilter} onChange={e=>setDateFilter(e.target.value)} /><label style={{display:'flex',alignItems:'center',gap:6,fontSize:13}}><input type="checkbox" checked={showAllDates} onChange={e=>setShowAllDates(e.target.checked)} /> 全部日期</label></div><div className="log-list">{filteredList.length===0?<p className="setting-text">暂无记录</p>:filteredList.map(l=>{ if(l.type==='feed'){ const f=l as FeedLog; return <div key={f.id} className="log-item"><span className="log-badge feed">🍼 喝奶</span><span className="log-time">{f.date} {toTimeLabel(new Date(f.startAt))} - {toTimeLabel(new Date(f.endAt))}</span><span className="log-dur">{formatDuration(f.durationSec)}（{formatDurationMin(f.durationSec)}分）</span>{f.note&&<span className="log-note">{f.note}</span>}<button className="btn" onClick={()=>handleDelete(f.id)}>删除</button></div>} else if(l.type==='poop'){ const p=l as PoopLog; return <div key={p.id} className="log-item"><span className="log-badge poop">💩 拉屎</span><span className="log-time">{p.date} {toTimeLabel(new Date(p.createdAt))}</span>{p.consistency&&<span className="chip">{p.consistency}</span>}{p.note&&<span className="log-note">{p.note}</span>}<button className="btn" onClick={()=>handleDelete(p.id)}>删除</button></div>} else { const s=l as SleepLog; return <div key={s.id} className="log-item"><span className="log-badge" style={{background:'#e0f0ff', color:'#2a6db5'}}>🌙 睡觉</span><span className="log-time">{formatDateTimeLabel(new Date(s.startAt))} - {formatDateTimeLabel(new Date(s.endAt))}</span><span className="log-dur">{formatSleepDuration(s.durationSec)}</span>{s.sleepType&&<span className="chip">{s.sleepType}</span>}{s.note&&<span className="log-note">{s.note}</span>}<button className="btn" onClick={()=>handleDelete(s.id)}>删除</button></div>}})}</div></div>
    <div className="setting-card"><div className="setting-title">导出报表（CSV 仅明细，汇总由图表承担）</div><p className="setting-text">按日期区间导出，含中文表头，Excel 直接打开不乱码。</p><div className="action-bar"><input className="select" type="date" value={exportStart} onChange={e=>setExportStart(e.target.value)} /><span style={{alignSelf:'center'}}>至</span><input className="select" type="date" value={exportEnd} onChange={e=>setExportEnd(e.target.value)} /><button className="btn primary" onClick={()=>{ if(exportStart>exportEnd){ setHint('开始日期需早于结束日期'); return } exportLogsCsv(logs,exportStart,exportEnd); setHint('已导出 CSV'); window.setTimeout(()=>setHint(''),2000)}}>导出 CSV</button></div></div>
  </>)
}
